### ISSUE TITLE
Gibberish in sign filename

### ISSUE THREAD

**Issue by JeS24** [sdgniser/data_collection#1]
## Issue:
When another submission is made for the same `app_no`, the image file for `sign` (and not `photo`) has gibberish in its name.

## Observations:
* Happens alternately.
* The problem is most probably in `views.py`, when the signature image data is decoded and then converted to a .PNG. (Check [Line 30-36 in views.py](https://github.com/sdgniser/data_collection/blob/5b697af3ca0ee4c5a24671ad9e6db6a87e05ce40/collect/views.py#L30-L36))

## Potential fix or Resources:
See how `ImageField.save()` works and if some other decoding process will help.

**Comment by 11DE784A** [comment]
Pushed a fix in #3

**Comment by JeS24** [comment]
Fixed via #6 .
