### ISSUE TITLE
Message persists after submission is completed

### ISSUE THREAD

**Issue by JeS24** [sdgniser/data_collection#11]
This message persists (text in green, below), even after submission and a hard refresh of the page. Any way to make it go away, after a submission is over or when the page is refreshed?

![image](https://user-images.githubusercontent.com/31299799/85321265-094ef700-b4e2-11ea-9427-0a9bff4e4267.png)

**Comment by Abhishek-Deshmukh** [comment]
It was already there I just styles it and stuff.
But isn't it supposed to show up after submission to show that it was uploaded properly?

**Comment by JeS24** [comment]
It is supposed to show up, but it stays, even after page is refreshed. I think, I should add this to the issue text above.

**Comment by JeS24** [comment]
Let's talk on Slack.

**Comment by Abhishek-Deshmukh** [comment]
add this in `/collect/static/js/scripts.js`
```javascript
if (performance.navigation.type == 1){$("$footer-message").hide();}
```
inside the `$(document).ready`'s function

**Comment by JeS24** [comment]
Hmm, we don't want to stop people from resubmitting, per se, as that's default behaviour.

**Comment by JeS24** [comment]
I am using this to fix it. https://stackoverflow.com/a/15278680
