### ISSUE TITLE
Add drag and drop to image upload.

### ISSUE THREAD

**Issue by Alpha3125** [sdgniser/data_collection#28]
This could help in putting photos faster.

*(Never knew this repo even existed)*

**Comment by JeS24** [comment]
Off topic. The app is intended to be used on tablets with stylus, as the [`README`](https://github.com/sdgniser/data_collection/blob/master/README.md) specifies. Closing for now.

Edit: Also, depending on the tablet OS (and even non-tablet, non-touch OS), drag & drop is already supported.
