### ISSUE TITLE
pressing 'Ctrl + Z' to undo the signature doesn't work  

### ISSUE THREAD

**Issue by DibyaBharatiPradhan** [sdgniser/data_collection#31]
# Bug
Clicking 'Ctrl +Z' while doing the signature on the white space removes the entries of the 'Name' and 'Application No.' sections.

# Improvement needed
There is no option to undo the signature. Also, there is no way to erase any mistake made while writing the signature in the white space. The 'clear' option removes the whole signature.
The users might want to undo the mistake made while signing instead of removing the whole signature.

# Suggested Implementation
Please add an 'Eraser' in the signature collector section.

**Comment by JeS24** [comment]
Off topic. The app is intended to be used on tablets with stylus, as the [`README`](https://github.com/sdgniser/data_collection/blob/master/README.md) specifies. Closing for now.

**Comment by JeS24** [comment]
Reopen this, if this feature is needed. There is a clear button IIRC.
